# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '021.LearnARC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 021.LearnARC

  target '021.LearnARCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '021.LearnARCUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod 'ReactiveObjC', '~> 3.1.0' 


end
